datadir: "results/amortized_msprime/AraTha_2epoch_genetic_map/data/"
posteriordir: "results/amortized_msprime/AraTha_2epoch_genetic_map/posterior/"
demog_model: "AraTha_2epoch_genetic_map"
ts_processor: "tskit_sfs"
embedding_net: "Identity"
n_sims_per_round : 1000
n_rounds : 20
n_ensemble: 10 # number of ensemble members