datadir: "results/amortized_msprime/AraTha_2epoch/data/"
posteriordir: "results/amortized_msprime/AraTha_2epoch/posterior/"
demog_model: "AraTha_2epoch"
ts_processor: "dinf"
n_snps: 20000
# originally n_snps = 2000
maf_thresh: 0.1
embedding_net: "ExchangeableCNN"
# originally, used channel size (1,5) and stride = (1,2), increased to (1, 50) and stride (1, 25) to use bigger genotype matrix without too much memory increase
n_sims_per_round : 1000
n_rounds : 20
n_ensemble: 10 # number of ensemble members
device: "cpu"