datadir: "results/amortized_msprime/AraTha_2epoch_genetic_map/data/"
posteriordir: "results/amortized_msprime/AraTha_2epoch_genetic_map/posterior/"
demog_model: "AraTha_2epoch_genetic_map"
ts_processor: "dinf"
n_snps: 20000
maf_thresh: 0.1
embedding_net: "ExchangeableCNN"
n_sims_per_round : 1000
n_rounds : 20
n_ensemble: 10 # number of ensemble members
device: "cpu"