datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "moments_LD_stats2"
embedding_net: "MLP"
n_sims : 100
n_trains : [1e2]
pops : ["YRI", "CEU"]
n_ensemble: 5 # number of ensemble members