datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "dinf_multiple_pops"
embedding_net: "ExchangeableCNN"
n_sims : 10000
n_trains : [1e3, 3e3, 1e4]
n_snps : 20000
n_ensemble: 10 # number of ensemble members