datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "dinf_multiple_pops"
embedding_net: "ExchangeableCNN"
n_sims_per_round : 1000
n_rounds : 2
n_snps : 20000
n_ensemble: 5 # number of ensemble members