n_train_sims: 3 # number of simulations per rounds
datadir: "results/gammaDFE_cnst_N/data/"
posteriordir: "results/gammaDFE_cnst_N/posterior/"
demog_model: "gammaDFE_cnst_N"
ts_processor: "three_channel_feature_matrices"
n_snps: 2000 # number of SNPs to use (for dinf)
embedding_net: "ExchangeableCNN"
total_rounds: 3 # number of rounds
N: 100 # population size