n_sims_per_round : 1000
n_rounds : 10
datadir: "results/amortized_dadi/AraTha_2epoch/data/"
posteriordir: "results/amortized_dadi/AraTha_2epoch/posterior/"
demog_model: "AraTha_2epoch"
embedding_net: "Identity"
n_ensemble: 10
